[package]
name = "pluto_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
reqwest = {version = "^0.11", features = ["blocking"]}
serde_json = "1.0.93"
tray-item = "^0.7"
